

#BEGIN-UID.userconfigs

#END-UID.userconfigs


development:
    database: ontorave_development
    adapter: mysql2
    pool: 5
    host: 127.0.0.1
    port: 3306
    encoding: utf8
    username: root
    password: 

test:
    adapter: mysql
    database: ontorave_test
    username: root
    password: 
    host: localhost
    port: 3306
    encoding: utf8

production:
    database: ontorave_development
    adapter: mysql2
    pool: 5
    host: 127.0.0.1
    port: 3306
    encoding: utf8
    username: root
    password: 
